# -*- coding: utf-8 -*-

#-----------------------------------------------------------------------------
# Python source generated by wxDesigner from file: wxhttpupload.wdr
# Do not modify this file, all changes will be lost!
#-----------------------------------------------------------------------------

# Include wxWindows' modules
import wx
import wx.grid

# Window functions

ID_BUTTON_UPLOAD_CONFIG = 10000
ID_CHOICE_UPLOAD_CONFIGURATIONS = 10001
ID_BUTTON_UPLOAD_CONFIGFOLDER = 10002
ID_TEXT_UPLOAD_CONFIGFOLDER = 10003
ID_BUTTON_ZULU_FOLDER = 10004
ID_TEXTCTRL_ZULU_FOLDER = 10005
ID_LINE = 10006
ID_BUTTON_ZULU_ERRORLOG = 10007
ID_CHECKBOX_AUTOZULU = 10008
ID_BUTTON_ZULU_GO = 10009
ID_BUTTON_ZULU_UPLOAD_GO = 10010
ID_BUTTON_LOCAL = 10011
ID_TEXTCTRL_UPLOAD_LOCAL = 10012
ID_BUTTON_REMOTE = 10013
ID_TEXTCTRL_UPLOAD_REMOTE = 10014
ID_TEXT = 10015
ID_TEXTCTRL_UPLOAD_USER = 10016
ID_TEXTCTRL_UPLOAD_PASSWORD = 10017
ID_BUTTON_UPLOAD_ERRORLOG = 10018
ID_CHECKBOX_AUTOUPLOAD = 10019
ID_BUTTON_UPLOAD_WEBDRIVE = 10020
ID_TEXTCTRL_UPLOAD_WEBDRIVE = 10021
ID_BUTTON_UPLOAD_FORCE = 10022
ID_BUTTON_UPLOAD_GO = 10023
ID_TEXTCTRL_LOG = 10024
ID_TEXT_STATUS = 10025

def tabbedDialogFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    item0.AddGrowableCol( 0 )
    item0.AddGrowableRow( 3 )
    
    item1 = wx.FlexGridSizer( 0, 2, 0, 0 )
    item1.AddGrowableCol( 1 )
    
    item2 = wx.Button( parent, ID_BUTTON_UPLOAD_CONFIG, "Configfile:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item1.Add( item2, 0, wx.ALIGN_CENTER|wx.ALL, 0 )

    item3 = wx.Choice( parent, ID_CHOICE_UPLOAD_CONFIGURATIONS, wx.DefaultPosition, [100,-1], [], 0 )
    item1.Add( item3, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 0 )

    item4 = wx.Button( parent, ID_BUTTON_UPLOAD_CONFIGFOLDER, "{CONFIG}", wx.DefaultPosition, wx.DefaultSize, 0 )
    item1.Add( item4, 0, wx.ALIGN_CENTER, 0 )

    item5 = wx.StaticText( parent, ID_TEXT_UPLOAD_CONFIGFOLDER, "....X....", wx.DefaultPosition, wx.DefaultSize, 0 )
    item1.Add( item5, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 10 )

    item7 = wx.StaticBox( parent, -1, "Zulu" )
    item6 = wx.StaticBoxSizer( item7, wx.VERTICAL )
    
    item8 = wx.FlexGridSizer( 0, 1, 0, 0 )
    item8.AddGrowableCol( 0 )
    item8.AddGrowableRow( 0 )
    
    item9 = wx.FlexGridSizer( 0, 2, 0, 0 )
    item9.AddGrowableCol( 1 )
    
    item10 = wx.Button( parent, ID_BUTTON_ZULU_FOLDER, "Folder:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item9.Add( item10, 0, wx.ALIGN_CENTER|wx.ALL, 0 )

    item11 = wx.TextCtrl( parent, ID_TEXTCTRL_ZULU_FOLDER, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item9.Add( item11, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 0 )

    item8.Add( item9, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item12 = wx.StaticLine( parent, ID_LINE, wx.DefaultPosition, wx.DefaultSize, wx.LI_HORIZONTAL )
    item8.Add( item12, 0, wx.GROW|wx.ALL, 0 )

    item13 = wx.FlexGridSizer( 1, 0, 0, 0 )
    item13.AddGrowableCol( 2 )
    
    item14 = wx.Button( parent, ID_BUTTON_ZULU_ERRORLOG, "Show ErrorLog", wx.DefaultPosition, wx.DefaultSize, 0 )
    item13.Add( item14, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item15 = wx.CheckBox( parent, ID_CHECKBOX_AUTOZULU, "Autozulu", wx.DefaultPosition, wx.DefaultSize, 0 )
    item13.Add( item15, 0, wx.ALIGN_CENTER|wx.ALL, 0 )

    item16 = wx.StaticLine( parent, ID_LINE, wx.DefaultPosition, [-1,20], wx.LI_VERTICAL )
    item13.Add( item16, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 5 )

    item17 = wx.Button( parent, ID_BUTTON_ZULU_GO, "ZULU", wx.DefaultPosition, wx.DefaultSize, 0 )
    item17.SetDefault()
    item13.Add( item17, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item18 = wx.Button( parent, ID_BUTTON_ZULU_UPLOAD_GO, "==> ZULU + Upload <==", wx.DefaultPosition, wx.DefaultSize, 0 )
    item13.Add( item18, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item8.Add( item13, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 0 )

    item6.Add( item8, 0, wx.GROW, 0 )

    item0.Add( item6, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item20 = wx.StaticBox( parent, -1, "wxhttpupload (WebDAV)" )
    item19 = wx.StaticBoxSizer( item20, wx.VERTICAL )
    
    item21 = wx.FlexGridSizer( 0, 1, 0, 0 )
    item21.AddGrowableCol( 0 )
    item21.AddGrowableRow( 0 )
    
    item22 = wx.FlexGridSizer( 0, 2, 0, 0 )
    item22.AddGrowableCol( 1 )
    
    item23 = wx.Button( parent, ID_BUTTON_LOCAL, "Local:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item22.Add( item23, 0, wx.ALIGN_CENTER|wx.ALL, 0 )

    item24 = wx.TextCtrl( parent, ID_TEXTCTRL_UPLOAD_LOCAL, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item22.Add( item24, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 0 )

    item25 = wx.Button( parent, ID_BUTTON_REMOTE, "Remote:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item22.Add( item25, 0, wx.ALIGN_CENTER|wx.ALL, 0 )

    item26 = wx.TextCtrl( parent, ID_TEXTCTRL_UPLOAD_REMOTE, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item22.Add( item26, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 0 )

    item27 = wx.StaticText( parent, ID_TEXT, "User:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item22.Add( item27, 0, wx.ALIGN_CENTER|wx.ALL, 0 )

    item28 = wx.TextCtrl( parent, ID_TEXTCTRL_UPLOAD_USER, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item22.Add( item28, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 0 )

    item29 = wx.StaticText( parent, ID_TEXT, "Password:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item22.Add( item29, 0, wx.ALIGN_CENTER|wx.ALL, 0 )

    item30 = wx.TextCtrl( parent, ID_TEXTCTRL_UPLOAD_PASSWORD, "", wx.DefaultPosition, wx.DefaultSize, wx.TE_PASSWORD )
    item22.Add( item30, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 0 )

    item21.Add( item22, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item31 = wx.StaticLine( parent, ID_LINE, wx.DefaultPosition, [20,-1], wx.LI_HORIZONTAL )
    item21.Add( item31, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 0 )

    item32 = wx.FlexGridSizer( 1, 0, 0, 0 )
    item32.AddGrowableCol( 2 )
    
    item33 = wx.Button( parent, ID_BUTTON_UPLOAD_ERRORLOG, "Show ErrorLog", wx.DefaultPosition, wx.DefaultSize, 0 )
    item32.Add( item33, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item34 = wx.CheckBox( parent, ID_CHECKBOX_AUTOUPLOAD, "Autoupload", wx.DefaultPosition, wx.DefaultSize, 0 )
    item32.Add( item34, 0, wx.ALIGN_CENTER|wx.ALL, 0 )

    item35 = wx.StaticLine( parent, ID_LINE, wx.DefaultPosition, [-1,20], wx.LI_VERTICAL )
    item32.Add( item35, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item36 = wx.Button( parent, ID_BUTTON_UPLOAD_WEBDRIVE, "Mount", wx.DefaultPosition, wx.DefaultSize, 0 )
    item32.Add( item36, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item37 = wx.TextCtrl( parent, ID_TEXTCTRL_UPLOAD_WEBDRIVE, "", wx.DefaultPosition, [28,-1], 0 )
    item32.Add( item37, 0, wx.ALIGN_CENTER, 0 )

    item38 = wx.StaticLine( parent, ID_LINE, wx.DefaultPosition, [-1,20], wx.LI_VERTICAL )
    item32.Add( item38, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 5 )

    item39 = wx.Button( parent, ID_BUTTON_UPLOAD_FORCE, "Force Upload", wx.DefaultPosition, wx.DefaultSize, 0 )
    item32.Add( item39, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item40 = wx.Button( parent, ID_BUTTON_UPLOAD_GO, "==> Upload <==", wx.DefaultPosition, wx.DefaultSize, 0 )
    item40.SetDefault()
    item32.Add( item40, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item21.Add( item32, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 0 )

    item19.Add( item21, 0, wx.GROW, 35 )

    item0.Add( item19, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item41 = wx.TextCtrl( parent, ID_TEXTCTRL_LOG, "", wx.DefaultPosition, wx.DefaultSize, wx.TE_MULTILINE|wx.VSCROLL|wx.HSCROLL )
    item0.Add( item41, 0, wx.GROW, 5 )

    item42 = wx.StaticText( parent, ID_TEXT_STATUS, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item0.Add( item42, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

# Menubar functions

# Toolbar functions

# Bitmap functions


# End of generated file
